version: "3"
services:
  server:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_MYSQL_HOST=mysqldb
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"

networks:
  springmysql-net: